// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlxfFUBubLJuyEPXWCiyB3kXNrebdM0ws',
    appId: '1:1029851419163:web:ff7e20ade83e1354355ebe',
    messagingSenderId: '1029851419163',
    projectId: 'flutter-test-2ef3d',
    authDomain: 'flutter-test-2ef3d.firebaseapp.com',
    storageBucket: 'flutter-test-2ef3d.appspot.com',
    measurementId: 'G-JZZHJB8K12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM_704BiwLmvVW_rBVIt6Uo0hNDXRzy-E',
    appId: '1:1029851419163:android:c5e485349703c0da355ebe',
    messagingSenderId: '1029851419163',
    projectId: 'flutter-test-2ef3d',
    storageBucket: 'flutter-test-2ef3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlBO7a0Zfg25eQRebpBFrQe90PSCL_9hc',
    appId: '1:1029851419163:ios:ee964bcac2348ed8355ebe',
    messagingSenderId: '1029851419163',
    projectId: 'flutter-test-2ef3d',
    storageBucket: 'flutter-test-2ef3d.appspot.com',
    iosClientId: '1029851419163-2u68o7vnbbehmrukg11d6vtrrhq9vihj.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicRegistration',
  );
}
